// src/config/problem-categories.ts
import type { ProblemCategory } from "@/components/map/types/map";
import { PROBLEM_TYPES } from "@/constants/map-constants";

export const PROBLEM_CATEGORIES: ProblemCategory[] = [
  {
    id: "BURACO",
    type: PROBLEM_TYPES.BURACO,
    label: "Buraco",
    icon: "/map-icons/buraco.png",
    bgColor: "bg-red-100",
    mapIcon: {
      iconUrl: "https://unpkg.com/leaflet@1.9.4/dist/images/marker-icon.png",
      iconRetinaUrl: "https://unpkg.com/leaflet@1.9.4/dist/images/marker-icon-2x.png",
      shadowUrl: "https://unpkg.com/leaflet@1.9.4/dist/images/marker-shadow.png",
      iconSize: [25, 41],
      iconAnchor: [12, 41],
      popupAnchor: [1, -34],
      shadowSize: [41, 41],
    },
    subcategories: [
      {
        id: "BUEIRO_ABERTO",
        type: PROBLEM_TYPES.BUEIRO_ABERTO,
        label: "Bueiro Aberto",
        icon: "/map-icons/bueiro-aberto.png",
        mapIcon: {
          iconUrl: "https://unpkg.com/leaflet@1.9.4/dist/images/marker-icon.png",
          iconRetinaUrl: "https://unpkg.com/leaflet@1.9.4/dist/images/marker-icon-2x.png",
          shadowUrl: "https://unpkg.com/leaflet@1.9.4/dist/images/marker-shadow.png",
          iconSize: [25, 41],
          iconAnchor: [12, 41],
          popupAnchor: [1, -34],
          shadowSize: [41, 41],
        },
      },
      {
        id: "BUEIRO_VAZAMENTO",
        type: PROBLEM_TYPES.BUEIRO_VAZAMENTO,
        label: "Bueiro Vazamento",
        icon: "/map-icons/bueiro-vazamento.png",
        mapIcon: {
          iconUrl: "https://unpkg.com/leaflet@1.9.4/dist/images/marker-icon.png",
          iconRetinaUrl: "https://unpkg.com/leaflet@1.9.4/dist/images/marker-icon-2x.png",
          shadowUrl: "https://unpkg.com/leaflet@1.9.4/dist/images/marker-shadow.png",
          iconSize: [25, 41],
          iconAnchor: [12, 41],
          popupAnchor: [1, -34],
          shadowSize: [41, 41],
        },
      },
    ],
  },
  {
    id: "ALERTA",
    type: PROBLEM_TYPES.ALERTA,
    label: "Alerta",
    icon: "/map-icons/alerta.png",
    bgColor: "bg-yellow-100",
    mapIcon: {
      iconUrl: "https://unpkg.com/leaflet@1.9.4/dist/images/marker-icon.png",
      iconRetinaUrl: "https://unpkg.com/leaflet@1.9.4/dist/images/marker-icon-2x.png",
      shadowUrl: "https://unpkg.com/leaflet@1.9.4/dist/images/marker-shadow.png",
      iconSize: [25, 41],
      iconAnchor: [12, 41],
      popupAnchor: [1, -34],
      shadowSize: [41, 41],
    },
    subcategories: [
      {
        id: "BLITZ",
        type: PROBLEM_TYPES.BLITZ,
        label: "Blitz",
        icon: "/map-icons/blitz.png",
        mapIcon: {
          iconUrl: "https://unpkg.com/leaflet@1.9.4/dist/images/marker-icon.png",
          iconRetinaUrl: "https://unpkg.com/leaflet@1.9.4/dist/images/marker-icon-2x.png",
          shadowUrl: "https://unpkg.com/leaflet@1.9.4/dist/images/marker-shadow.png",
          iconSize: [25, 41],
          iconAnchor: [12, 41],
          popupAnchor: [1, -34],
          shadowSize: [41, 41],
        },
      },
      {
        id: "PISTA",
        type: PROBLEM_TYPES.PISTA,
        label: "Pista",
        icon: "/map-icons/pista.png",
        mapIcon: {
          iconUrl: "https://unpkg.com/leaflet@1.9.4/dist/images/marker-icon.png",
          iconRetinaUrl: "https://unpkg.com/leaflet@1.9.4/dist/images/marker-icon-2x.png",
          shadowUrl: "https://unpkg.com/leaflet@1.9.4/dist/images/marker-shadow.png",
          iconSize: [25, 41],
          iconAnchor: [12, 41],
          popupAnchor: [1, -34],
          shadowSize: [41, 41],
        },
      },
      {
        id: "TIROTEIO",
        type: PROBLEM_TYPES.TIROTEIO,
        label: "Tiroteio",
        icon: "/map-icons/tiroteio.png",
        mapIcon: {
          iconUrl: "https://unpkg.com/leaflet@1.9.4/dist/images/marker-icon.png",
          iconRetinaUrl: "https://unpkg.com/leaflet@1.9.4/dist/images/marker-icon-2x.png",
          shadowUrl: "https://unpkg.com/leaflet@1.9.4/dist/images/marker-shadow.png",
          iconSize: [25, 41],
          iconAnchor: [12, 41],
          popupAnchor: [1, -34],
          shadowSize: [41, 41],
        },
      },
    ],
  },
  {
    id: "ILUMINACAO",
    type: PROBLEM_TYPES.ILUMINACAO,
    label: "Iluminação",
    icon: "/map-icons/iluminacao-publica.png",
    bgColor: "bg-blue-100",
    mapIcon: {
      iconUrl: "https://unpkg.com/leaflet@1.9.4/dist/images/marker-icon.png",
      iconRetinaUrl: "https://unpkg.com/leaflet@1.9.4/dist/images/marker-icon-2x.png",
      shadowUrl: "https://unpkg.com/leaflet@1.9.4/dist/images/marker-shadow.png",
      iconSize: [25, 41],
      iconAnchor: [12, 41],
      popupAnchor: [1, -34],
      shadowSize: [41, 41],
    },
    subcategories: [
      {
        id: "SEMAFARO",
        type: PROBLEM_TYPES.SEMAFARO,
        label: "Semáfaro",
        icon: "/map-icons/semafaro.png",
        mapIcon: {
          iconUrl: "https://unpkg.com/leaflet@1.9.4/dist/images/marker-icon.png",
          iconRetinaUrl: "https://unpkg.com/leaflet@1.9.4/dist/images/marker-icon-2x.png",
          shadowUrl: "https://unpkg.com/leaflet@1.9.4/dist/images/marker-shadow.png",
          iconSize: [25, 41],
          iconAnchor: [12, 41],
          popupAnchor: [1, -34],
          shadowSize: [41, 41],
        },
      },
    ],
  },
  {
    id: "INCENDIO",
    type: PROBLEM_TYPES.INCENDIO,
    label: "Incendio",
    icon: "/map-icons/incendio.png",
    bgColor: "bg-blue-100",
    mapIcon: {
      iconUrl: "https://unpkg.com/leaflet@1.9.4/dist/images/marker-icon.png",
      iconRetinaUrl: "https://unpkg.com/leaflet@1.9.4/dist/images/marker-icon-2x.png",
      shadowUrl: "https://unpkg.com/leaflet@1.9.4/dist/images/marker-shadow.png",
      iconSize: [25, 41],
      iconAnchor: [12, 41],
      popupAnchor: [1, -34],
      shadowSize: [41, 41],
    },
    subcategories: [
      {
        id: "INCENDIO_CARRO",
        type: PROBLEM_TYPES.INCENDIO_CARRO,
        label: "Incendio Carro",
        icon: "/map-icons/incendio-carro.png",
        mapIcon: {
          iconUrl: "https://unpkg.com/leaflet@1.9.4/dist/images/marker-icon.png",
          iconRetinaUrl: "https://unpkg.com/leaflet@1.9.4/dist/images/marker-icon-2x.png",
          shadowUrl: "https://unpkg.com/leaflet@1.9.4/dist/images/marker-shadow.png",
          iconSize: [25, 41],
          iconAnchor: [12, 41],
          popupAnchor: [1, -34],
          shadowSize: [41, 41],
        },
      },
      {
        id: "INCENDIO_CASA",
        type: PROBLEM_TYPES.INCENDIO_CASA,
        label: "Incendio Casa",
        icon: "/map-icons/incendio-casa.png",
        mapIcon: {
          iconUrl: "https://unpkg.com/leaflet@1.9.4/dist/images/marker-icon.png",
          iconRetinaUrl: "https://unpkg.com/leaflet@1.9.4/dist/images/marker-icon-2x.png",
          shadowUrl: "https://unpkg.com/leaflet@1.9.4/dist/images/marker-shadow.png",
          iconSize: [25, 41],
          iconAnchor: [12, 41],
          popupAnchor: [1, -34],
          shadowSize: [41, 41],
        },
      },
      {
        id: "INCENDIO_FLORESTA",
        type: PROBLEM_TYPES.INCENDIO_FLORESTA,
        label: "Incendio Floresta",
        icon: "/map-icons/incendio-floresta.png",
        mapIcon: {
          iconUrl: "https://unpkg.com/leaflet@1.9.4/dist/images/marker-icon.png",
          iconRetinaUrl: "https://unpkg.com/leaflet@1.9.4/dist/images/marker-icon-2x.png",
          shadowUrl: "https://unpkg.com/leaflet@1.9.4/dist/images/marker-shadow.png",
          iconSize: [25, 41],
          iconAnchor: [12, 41],
          popupAnchor: [1, -34],
          shadowSize: [41, 41],
        },
      },
    ],
  },
  {
    id: "HIDRAULICA",
    type: PROBLEM_TYPES.HIDRAULICA,
    label: "Hidráulica",
    icon: "/map-icons/hidraulica.png",
    bgColor: "bg-blue-100",
    mapIcon: {
      iconUrl: "https://unpkg.com/leaflet@1.9.4/dist/images/marker-icon.png",
      iconRetinaUrl: "https://unpkg.com/leaflet@1.9.4/dist/images/marker-icon-2x.png",
      shadowUrl: "https://unpkg.com/leaflet@1.9.4/dist/images/marker-shadow.png",
      iconSize: [25, 41],
      iconAnchor: [12, 41],
      popupAnchor: [1, -34],
      shadowSize: [41, 41],
    },
    subcategories: [
      {
        id: "CANO_QUEBRADO",
        type: PROBLEM_TYPES.CANO_QUEBRADO,
        label: "Cano Quebrado",
        icon: "/map-icons/cano-quebrado.png",
        mapIcon: {
          iconUrl: "https://unpkg.com/leaflet@1.9.4/dist/images/marker-icon.png",
          iconRetinaUrl: "https://unpkg.com/leaflet@1.9.4/dist/images/marker-icon-2x.png",
          shadowUrl: "https://unpkg.com/leaflet@1.9.4/dist/images/marker-shadow.png",
          iconSize: [25, 41],
          iconAnchor: [12, 41],
          popupAnchor: [1, -34],
          shadowSize: [41, 41],
        },
      },
    ],
  },
];
